### ISSUE TITLE
Enable contributors

### ISSUE THREAD

**Issue by malukenho** [codelicia/xulieta#11]
It is currently already enabled at the org level.
We just need to use it here 👯

**Comment by EHER** [comment]
@all-contributors please add @malukenho for infrastructure, maintenance and code

**Comment by EHER** [comment]
@all-contributors please add @EHER for infrastructure, maintenance and code

**Comment by EHER** [comment]
@all-contributors please add @malukenho for infrastructure, maintenance and code

**Comment by malukenho** [comment]
@all-contributors please add @airtonzanon for review

**Comment by EHER** [comment]
I think we may close this one :)

**Comment by malukenho** [comment]
As per @EHER suggestion, I'm closing this one! 🙏🏻
