### ISSUE TITLE
Xulieta plugins

### ISSUE THREAD

**Issue by malukenho** [codelicia/xulieta#32]
- [x] Auto enable plugins when `composer install`?
- [x] Document a simple plugin creation

**Comment by szepeviktor** [comment]
Does it mean I will be able to run PHPCS on snippets?

**Comment by malukenho** [comment]
You are already able to do it if you want via plugins.
But you actually gave us a good idea to be put in a tutorial. Thanks for that. 😄 

Another alternative for a tutorial subject could be a plugin for validating JSON.
A call for `json_encode/decode` could do the job.

**Comment by EHER** [comment]
We started a plugin [here](https://github.com/codelicia/xulieta-json) as example. 👍🏻
